### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ammarsasfe** [izulwahidin/mutasi-qris.id#1]
Nominal diatas ratusan return [] / null

**Comment by affisjunianto** [comment]
> Nominal diatas ratusan return [] / null

ini work beneran ya check mutasi nya?

**Comment by izulwahidin** [comment]
Maaf gan, saya belum bisa fix masalah ini, soalnya QRIS saya nominalnya tidak ada yg di atas ratusan :(

**Comment by affisjunianto** [comment]
> Maaf gan, saya belum bisa fix masalah ini, soalnya QRIS saya nominalnya tidak ada yg di atas ratusan :(

bang. gw bantu. tapi uang nya bisa di balikin gak hehe

**Comment by izulwahidin** [comment]
solved
