### ISSUE TITLE
Tidak bisa login

### ISSUE THREAD

**Issue by dwiepalu** [izulwahidin/mutasi-qris.id#3]
Apakah script ini masih berfungsi? soalnya muncul error "Tidak dapat login, Harap cek kembali email & password anda" padahal email dan password sudah sesuai
![Screenshot_35](https://github.com/izulwahidin/mutasi-qris.id/assets/26091042/1d7310f8-5af9-4afe-b726-947d967dbaf3)

**Comment by izulwahidin** [comment]
udah fix
